//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsInventoryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int orderid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> noofitems { get; set; }
        public Nullable<double> Totalprice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
