//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsInventoryMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUsers_New
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> roleid { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
